apiVersion: v2
name: mgob
description: |
  MongoDB dockerized backup agent.
  Runs scheduled backups with retention, S3 & SFTP upload, notifications, instrumentation with Prometheus and more.


version: 1.2.0
appVersion: "1.3"

sources:
- https://github.com/stefanprodan/mgob

maintainers:
- name: endrec
  email: endre.czirbesz@rungway.com
